### ISSUE TITLE
Can't exit weird mode

### ISSUE THREAD

**Issue by deftk** [backenddevgg/some-graph-display-website#1]
I'm on a mobile device and can't exit the weird mode. Please fix!!

**Comment by backenddevgg** [comment]
Fixed by adding an alert with instructions to exit.
`alert('Well... If you use mobile just reload the website to quit.\nThe worst that will happen is you losing your input function.');` (index.html, line 101)

**Comment by deftk** [comment]
Well, this did not _fix_ the issue

**Comment by backenddevgg** [comment]
That is not a problem. Therefore I am not going to _"fix"_ this. Just connect a keyboard to your phone or use a PC instead.

**Comment by deftk** [comment]
I don't own a keyboard I can plug into my phone. Do you suggest that I am supposed to buy a keyboard and adapter now?

**Comment by backenddevgg** [comment]
Another way is to install a keyboard emulator onto your phone. This could be a cheaper solution to your issue. However, I appreciate your decision to use **Some Graph Display Website**. Thank you very much for using this product.

If you have an idea how to improve this product please let me know.
